### ISSUE TITLE
Add --with-children flag to filter reads for tax ID and children

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#115] opened 2018-09-25 16:17 UTC
Right now, the `filter_reads` command only works with tax ID's passed specifically on the command line, but most users will actually want to be able to pull reads for a tax ID and all children (i.e. pull all reads for a genus).

**Comment by boydgreenfield** [comment] 2018-09-26 16:10
Closing as a dupe of #114

**Closed by boydgreenfield** 2018-09-26 16:10 UTC
